// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pushnotifications.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import pushnotifications.implementation.apn.APNConnection;

public class SendAppleMessages extends CustomJavaAction<java.lang.Boolean>
{
	private java.util.List<IMendixObject> __messages;
	private java.util.List<pushnotifications.proxies.AppleMessage> messages;

	public SendAppleMessages(IContext context, java.util.List<IMendixObject> messages)
	{
		super(context);
		this.__messages = messages;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.messages = new java.util.ArrayList<pushnotifications.proxies.AppleMessage>();
		if (__messages != null)
			for (IMendixObject __messagesElement : __messages)
				this.messages.add(pushnotifications.proxies.AppleMessage.initialize(getContext(), __messagesElement));

		// BEGIN USER CODE
		APNConnection connection = APNConnection.getConnection();
		connection.sendMessages(messages);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SendAppleMessages";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
