// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pushnotifications.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import pushnotifications.proxies.Message;
import static pushnotifications.proxies.microflows.Microflows.createAndSendMessageToDevice;

/**
 * Java action to use instead of microflow 'SendMessageImmediately'
 * Parameters: 
 * Device: Android or iOS
 * MessageText: the contents of the message
 * Title: The title of the message
 * Badge: a number that appears on the app icon (iOS)
 * LaunchImage: file name of the launch image (iOS)
 * Sound: name of system sound to play (iOS)
 * 
 */
public class SendMessageToDevice extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __MessageData;
	private pushnotifications.proxies.MessageData MessageData;
	private IMendixObject __Device;
	private pushnotifications.proxies.Device Device;

	public SendMessageToDevice(IContext context, IMendixObject MessageData, IMendixObject Device)
	{
		super(context);
		this.__MessageData = MessageData;
		this.__Device = Device;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.MessageData = __MessageData == null ? null : pushnotifications.proxies.MessageData.initialize(getContext(), __MessageData);

		this.Device = __Device == null ? null : pushnotifications.proxies.Device.initialize(getContext(), __Device);

		// BEGIN USER CODE
		Message message = createAndSendMessageToDevice(getContext(), Device, MessageData);
		return message.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SendMessageToDevice";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
