// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotificationexampleimplementation.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the PushNotificationExampleImplementation module
	public static void aCT_Device_Delete(IContext context, java.util.List<pushnotifications.proxies.Device> _deviceList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> listparam_deviceList = null;
		if (_deviceList != null)
		{
			listparam_deviceList = new java.util.ArrayList<>();
			for (var obj : _deviceList) {
				listparam_deviceList.add(obj.getMendixObject());
			}
		}
		params.put("DeviceList", listparam_deviceList);

		Core.microflowCall("PushNotificationExampleImplementation.ACT_Device_Delete").withParams(params).execute(context);
	}
	public static boolean afterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("PushNotificationExampleImplementation.AfterStartup").withParams(params).execute(context);
	}
	public static void iVK_OpenSendMessageFormWithContext(IContext context, java.util.List<pushnotifications.proxies.Device> _devices)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> listparam_devices = null;
		if (_devices != null)
		{
			listparam_devices = new java.util.ArrayList<>();
			for (var obj : _devices) {
				listparam_devices.add(obj.getMendixObject());
			}
		}
		params.put("Devices", listparam_devices);

		Core.microflowCall("PushNotificationExampleImplementation.IVK_OpenSendMessageFormWithContext").withParams(params).execute(context);
	}
	public static void iVK_OpenSendMessageFormWithoutContext(IContext context, java.util.List<pushnotifications.proxies.Device> _devices)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> listparam_devices = null;
		if (_devices != null)
		{
			listparam_devices = new java.util.ArrayList<>();
			for (var obj : _devices) {
				listparam_devices.add(obj.getMendixObject());
			}
		}
		params.put("Devices", listparam_devices);

		Core.microflowCall("PushNotificationExampleImplementation.IVK_OpenSendMessageFormWithoutContext").withParams(params).execute(context);
	}
	public static void iVK_TestDeviceCleanupScheduledEvent(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("PushNotificationExampleImplementation.IVK_TestDeviceCleanupScheduledEvent").withParams(params).execute(context);
	}
	public static void iVK_TestMessageCleanupScheduledEvent(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("PushNotificationExampleImplementation.IVK_TestMessageCleanupScheduledEvent").withParams(params).execute(context);
	}
	public static void microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("PushNotificationExampleImplementation.Microflow").withParams(params).execute(context);
	}
}
