// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotificationexampleimplementation.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the PushNotificationExampleImplementation module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Device_DeleteBuilder(
		java.util.List<pushnotifications.proxies.Device> _deviceList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PushNotificationExampleImplementation.ACT_Device_Delete");
		builder = builder.withParam("DeviceList", _deviceList);
		return builder;
	}

	public static void aCT_Device_Delete(
		IContext context,
		java.util.List<pushnotifications.proxies.Device> _deviceList
	)
	{
		aCT_Device_DeleteBuilder(
				_deviceList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder afterStartupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PushNotificationExampleImplementation.AfterStartup");
		return builder;
	}

	public static boolean afterStartup(IContext context)
	{
		Object result = afterStartupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_OpenSendMessageFormWithContextBuilder(
		java.util.List<pushnotifications.proxies.Device> _devices
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PushNotificationExampleImplementation.IVK_OpenSendMessageFormWithContext");
		builder = builder.withParam("Devices", _devices);
		return builder;
	}

	public static void iVK_OpenSendMessageFormWithContext(
		IContext context,
		java.util.List<pushnotifications.proxies.Device> _devices
	)
	{
		iVK_OpenSendMessageFormWithContextBuilder(
				_devices
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_OpenSendMessageFormWithoutContextBuilder(
		java.util.List<pushnotifications.proxies.Device> _devices
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PushNotificationExampleImplementation.IVK_OpenSendMessageFormWithoutContext");
		builder = builder.withParam("Devices", _devices);
		return builder;
	}

	public static void iVK_OpenSendMessageFormWithoutContext(
		IContext context,
		java.util.List<pushnotifications.proxies.Device> _devices
	)
	{
		iVK_OpenSendMessageFormWithoutContextBuilder(
				_devices
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_TestDeviceCleanupScheduledEventBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PushNotificationExampleImplementation.IVK_TestDeviceCleanupScheduledEvent");
		return builder;
	}

	public static void iVK_TestDeviceCleanupScheduledEvent(IContext context)
	{
		iVK_TestDeviceCleanupScheduledEventBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_TestMessageCleanupScheduledEventBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PushNotificationExampleImplementation.IVK_TestMessageCleanupScheduledEvent");
		return builder;
	}

	public static void iVK_TestMessageCleanupScheduledEvent(IContext context)
	{
		iVK_TestMessageCleanupScheduledEventBuilder().execute(context);
	}
}
