// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PushNotificationInput
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pushNotificationInputMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PushNotificationInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Message("Message"),
		ActionName("ActionName"),
		WithContextObject("WithContextObject"),
		PushNotificationsInput_Device("MyFirstModule.PushNotificationsInput_Device");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PushNotificationInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.PushNotificationInput"));
	}

	protected PushNotificationInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pushNotificationInputMendixObject)
	{
		if (pushNotificationInputMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.PushNotificationInput", pushNotificationInputMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.PushNotificationInput");

		this.pushNotificationInputMendixObject = pushNotificationInputMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PushNotificationInput.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.PushNotificationInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.PushNotificationInput.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.PushNotificationInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PushNotificationInput(context, mendixObject);
	}

	public static myfirstmodule.proxies.PushNotificationInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PushNotificationInput.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Message
	 */
	public final String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of ActionName
	 */
	public final String getActionName()
	{
		return getActionName(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionName
	 */
	public final String getActionName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ActionName.toString());
	}

	/**
	 * Set value of ActionName
	 * @param actionname
	 */
	public final void setActionName(String actionname)
	{
		setActionName(getContext(), actionname);
	}

	/**
	 * Set value of ActionName
	 * @param context
	 * @param actionname
	 */
	public final void setActionName(com.mendix.systemwideinterfaces.core.IContext context, String actionname)
	{
		getMendixObject().setValue(context, MemberNames.ActionName.toString(), actionname);
	}

	/**
	 * @return value of WithContextObject
	 */
	public final Boolean getWithContextObject()
	{
		return getWithContextObject(getContext());
	}

	/**
	 * @param context
	 * @return value of WithContextObject
	 */
	public final Boolean getWithContextObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.WithContextObject.toString());
	}

	/**
	 * Set value of WithContextObject
	 * @param withcontextobject
	 */
	public final void setWithContextObject(Boolean withcontextobject)
	{
		setWithContextObject(getContext(), withcontextobject);
	}

	/**
	 * Set value of WithContextObject
	 * @param context
	 * @param withcontextobject
	 */
	public final void setWithContextObject(com.mendix.systemwideinterfaces.core.IContext context, Boolean withcontextobject)
	{
		getMendixObject().setValue(context, MemberNames.WithContextObject.toString(), withcontextobject);
	}

	/**
	 * @return value of PushNotificationsInput_Device
	 */
	public final pushnotifications.proxies.Device getPushNotificationsInput_Device() throws com.mendix.core.CoreException
	{
		return getPushNotificationsInput_Device(getContext());
	}

	/**
	 * @param context
	 * @return value of PushNotificationsInput_Device
	 */
	public final pushnotifications.proxies.Device getPushNotificationsInput_Device(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pushnotifications.proxies.Device result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PushNotificationsInput_Device.toString());
		if (identifier != null)
			result = pushnotifications.proxies.Device.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PushNotificationsInput_Device
	 * @param pushnotificationsinput_device
	 */
	public final void setPushNotificationsInput_Device(pushnotifications.proxies.Device pushnotificationsinput_device)
	{
		setPushNotificationsInput_Device(getContext(), pushnotificationsinput_device);
	}

	/**
	 * Set value of PushNotificationsInput_Device
	 * @param context
	 * @param pushnotificationsinput_device
	 */
	public final void setPushNotificationsInput_Device(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.Device pushnotificationsinput_device)
	{
		if (pushnotificationsinput_device == null)
			getMendixObject().setValue(context, MemberNames.PushNotificationsInput_Device.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PushNotificationsInput_Device.toString(), pushnotificationsinput_device.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pushNotificationInputMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PushNotificationInput that = (myfirstmodule.proxies.PushNotificationInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.PushNotificationInput";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
