// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the PushNotifications module

	public static String getLogNode()
	{
		return (String)Core.getConfiguration().getConstantValue("PushNotifications.LogNode");
	}

	public static Long getMaxFailedCount()
	{
		return (Long)Core.getConfiguration().getConstantValue("PushNotifications.MaxFailedCount");
	}
}