// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pushnotifications.actions;

import java.io.ByteArrayInputStream;
import java.util.Collections;
import java.util.List;
import com.google.auth.oauth2.GoogleCredentials;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class GetFCMAccessToken extends UserAction<java.lang.String>
{
	private final java.lang.String PrivateKey;

	public GetFCMAccessToken(
		IContext context,
		java.lang.String _privateKey
	)
	{
		super(context);
		this.PrivateKey = _privateKey;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<String> SCOPES = Collections.singletonList("https://www.googleapis.com/auth/firebase.messaging");
		
		GoogleCredentials credentials = GoogleCredentials
			.fromStream(new ByteArrayInputStream(this.PrivateKey.getBytes()))
			.createScoped(SCOPES);
		credentials.refreshIfExpired();

		return credentials.getAccessToken().getTokenValue();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFCMAccessToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
