// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pushnotifications.actions;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.io.ByteArrayInputStream;
import java.util.Collections;
import java.util.List;

public class GetFCMAccessToken extends CustomJavaAction<java.lang.String>
{
	private java.lang.String PrivateKey;

	public GetFCMAccessToken(IContext context, java.lang.String PrivateKey)
	{
		super(context);
		this.PrivateKey = PrivateKey;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<String> SCOPES = Collections.singletonList("https://www.googleapis.com/auth/firebase.messaging");

		GoogleCredential googleCredential = GoogleCredential
				.fromStream(new ByteArrayInputStream(this.PrivateKey.getBytes()))
				.createScoped(SCOPES);
		googleCredential.refreshToken();
		return googleCredential.getAccessToken();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFCMAccessToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
