// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pushnotifications.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import pushnotifications.implementation.apns.APNSConnection;
import com.mendix.systemwideinterfaces.core.UserAction;

public class SendAPNSMessage_Impl extends UserAction<java.lang.Boolean>
{
	/** @deprecated use message.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __message;
	private final pushnotifications.proxies.Message message;
	/** @deprecated use settings.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __settings;
	private final pushnotifications.proxies.APNSSettings settings;

	public SendAPNSMessage_Impl(
		IContext context,
		IMendixObject _message,
		IMendixObject _settings
	)
	{
		super(context);
		this.__message = _message;
		this.message = _message == null ? null : pushnotifications.proxies.Message.initialize(getContext(), _message);
		this.__settings = _settings;
		this.settings = _settings == null ? null : pushnotifications.proxies.APNSSettings.initialize(getContext(), _settings);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		APNSConnection apnsConnection = APNSConnection.getInstance();
		apnsConnection.sendMessage(settings, message);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendAPNSMessage_Impl";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
