// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class APNCertificate extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "PushNotifications.APNCertificate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PassCode("PassCode"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		APNSettings_APNCertificate("PushNotifications.APNSettings_APNCertificate");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public APNCertificate(IContext context)
	{
		this(context, Core.instantiate(context, "PushNotifications.APNCertificate"));
	}

	protected APNCertificate(IContext context, IMendixObject aPNCertificateMendixObject)
	{
		super(context, aPNCertificateMendixObject);
		if (!Core.isSubClassOf("PushNotifications.APNCertificate", aPNCertificateMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a PushNotifications.APNCertificate");
	}

	/**
	 * @deprecated Use 'APNCertificate.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pushnotifications.proxies.APNCertificate initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return pushnotifications.proxies.APNCertificate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.APNCertificate initialize(IContext context, IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.APNCertificate(context, mendixObject);
	}

	public static pushnotifications.proxies.APNCertificate load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.APNCertificate.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.APNCertificate> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<pushnotifications.proxies.APNCertificate> result = new java.util.ArrayList<pushnotifications.proxies.APNCertificate>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//PushNotifications.APNCertificate" + xpathConstraint))
			result.add(pushnotifications.proxies.APNCertificate.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of PassCode
	 */
	public final String getPassCode()
	{
		return getPassCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PassCode
	 */
	public final String getPassCode(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.PassCode.toString());
	}

	/**
	 * Set value of PassCode
	 * @param passcode
	 */
	public final void setPassCode(String passcode)
	{
		setPassCode(getContext(), passcode);
	}

	/**
	 * Set value of PassCode
	 * @param context
	 * @param passcode
	 */
	public final void setPassCode(IContext context, String passcode)
	{
		getMendixObject().setValue(context, MemberNames.PassCode.toString(), passcode);
	}

	/**
	 * @return value of APNSettings_APNCertificate
	 */
	public final pushnotifications.proxies.APNSettings getAPNSettings_APNCertificate() throws CoreException
	{
		return getAPNSettings_APNCertificate(getContext());
	}

	/**
	 * @param context
	 * @return value of APNSettings_APNCertificate
	 */
	public final pushnotifications.proxies.APNSettings getAPNSettings_APNCertificate(IContext context) throws CoreException
	{
		pushnotifications.proxies.APNSettings result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APNSettings_APNCertificate.toString());
		if (identifier != null)
			result = pushnotifications.proxies.APNSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of APNSettings_APNCertificate
	 * @param apnsettings_apncertificate
	 */
	public final void setAPNSettings_APNCertificate(pushnotifications.proxies.APNSettings apnsettings_apncertificate)
	{
		setAPNSettings_APNCertificate(getContext(), apnsettings_apncertificate);
	}

	/**
	 * Set value of APNSettings_APNCertificate
	 * @param context
	 * @param apnsettings_apncertificate
	 */
	public final void setAPNSettings_APNCertificate(IContext context, pushnotifications.proxies.APNSettings apnsettings_apncertificate)
	{
		if (apnsettings_apncertificate == null)
			getMendixObject().setValue(context, MemberNames.APNSettings_APNCertificate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.APNSettings_APNCertificate.toString(), apnsettings_apncertificate.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.APNCertificate that = (pushnotifications.proxies.APNCertificate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "PushNotifications.APNCertificate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
