// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class AppleMessage extends pushnotifications.proxies.Message
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "PushNotifications.AppleMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sound("Sound"),
		Badge("Badge"),
		ActionKey("ActionKey"),
		LaunchImage("LaunchImage"),
		LocalizedKey("LocalizedKey"),
		ResizeAlertBodyPostfix("ResizeAlertBodyPostfix"),
		DeviceType("DeviceType"),
		To("To"),
		MessageId("MessageId"),
		Message("Message"),
		Failed("Failed"),
		FailedReason("FailedReason"),
		FailedCount("FailedCount"),
		NextTry("NextTry"),
		Queued("Queued");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public AppleMessage(IContext context)
	{
		this(context, Core.instantiate(context, "PushNotifications.AppleMessage"));
	}

	protected AppleMessage(IContext context, IMendixObject appleMessageMendixObject)
	{
		super(context, appleMessageMendixObject);
		if (!Core.isSubClassOf("PushNotifications.AppleMessage", appleMessageMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a PushNotifications.AppleMessage");
	}

	/**
	 * @deprecated Use 'AppleMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pushnotifications.proxies.AppleMessage initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return pushnotifications.proxies.AppleMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.AppleMessage initialize(IContext context, IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.AppleMessage(context, mendixObject);
	}

	public static pushnotifications.proxies.AppleMessage load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.AppleMessage.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.AppleMessage> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<pushnotifications.proxies.AppleMessage> result = new java.util.ArrayList<pushnotifications.proxies.AppleMessage>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//PushNotifications.AppleMessage" + xpathConstraint))
			result.add(pushnotifications.proxies.AppleMessage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Sound
	 */
	public final String getSound()
	{
		return getSound(getContext());
	}

	/**
	 * @param context
	 * @return value of Sound
	 */
	public final String getSound(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Sound.toString());
	}

	/**
	 * Set value of Sound
	 * @param sound
	 */
	public final void setSound(String sound)
	{
		setSound(getContext(), sound);
	}

	/**
	 * Set value of Sound
	 * @param context
	 * @param sound
	 */
	public final void setSound(IContext context, String sound)
	{
		getMendixObject().setValue(context, MemberNames.Sound.toString(), sound);
	}

	/**
	 * @return value of Badge
	 */
	public final Integer getBadge()
	{
		return getBadge(getContext());
	}

	/**
	 * @param context
	 * @return value of Badge
	 */
	public final Integer getBadge(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Badge.toString());
	}

	/**
	 * Set value of Badge
	 * @param badge
	 */
	public final void setBadge(Integer badge)
	{
		setBadge(getContext(), badge);
	}

	/**
	 * Set value of Badge
	 * @param context
	 * @param badge
	 */
	public final void setBadge(IContext context, Integer badge)
	{
		getMendixObject().setValue(context, MemberNames.Badge.toString(), badge);
	}

	/**
	 * @return value of ActionKey
	 */
	public final String getActionKey()
	{
		return getActionKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionKey
	 */
	public final String getActionKey(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ActionKey.toString());
	}

	/**
	 * Set value of ActionKey
	 * @param actionkey
	 */
	public final void setActionKey(String actionkey)
	{
		setActionKey(getContext(), actionkey);
	}

	/**
	 * Set value of ActionKey
	 * @param context
	 * @param actionkey
	 */
	public final void setActionKey(IContext context, String actionkey)
	{
		getMendixObject().setValue(context, MemberNames.ActionKey.toString(), actionkey);
	}

	/**
	 * @return value of LaunchImage
	 */
	public final String getLaunchImage()
	{
		return getLaunchImage(getContext());
	}

	/**
	 * @param context
	 * @return value of LaunchImage
	 */
	public final String getLaunchImage(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.LaunchImage.toString());
	}

	/**
	 * Set value of LaunchImage
	 * @param launchimage
	 */
	public final void setLaunchImage(String launchimage)
	{
		setLaunchImage(getContext(), launchimage);
	}

	/**
	 * Set value of LaunchImage
	 * @param context
	 * @param launchimage
	 */
	public final void setLaunchImage(IContext context, String launchimage)
	{
		getMendixObject().setValue(context, MemberNames.LaunchImage.toString(), launchimage);
	}

	/**
	 * @return value of LocalizedKey
	 */
	public final String getLocalizedKey()
	{
		return getLocalizedKey(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalizedKey
	 */
	public final String getLocalizedKey(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.LocalizedKey.toString());
	}

	/**
	 * Set value of LocalizedKey
	 * @param localizedkey
	 */
	public final void setLocalizedKey(String localizedkey)
	{
		setLocalizedKey(getContext(), localizedkey);
	}

	/**
	 * Set value of LocalizedKey
	 * @param context
	 * @param localizedkey
	 */
	public final void setLocalizedKey(IContext context, String localizedkey)
	{
		getMendixObject().setValue(context, MemberNames.LocalizedKey.toString(), localizedkey);
	}

	/**
	 * @return value of ResizeAlertBodyPostfix
	 */
	public final String getResizeAlertBodyPostfix()
	{
		return getResizeAlertBodyPostfix(getContext());
	}

	/**
	 * @param context
	 * @return value of ResizeAlertBodyPostfix
	 */
	public final String getResizeAlertBodyPostfix(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ResizeAlertBodyPostfix.toString());
	}

	/**
	 * Set value of ResizeAlertBodyPostfix
	 * @param resizealertbodypostfix
	 */
	public final void setResizeAlertBodyPostfix(String resizealertbodypostfix)
	{
		setResizeAlertBodyPostfix(getContext(), resizealertbodypostfix);
	}

	/**
	 * Set value of ResizeAlertBodyPostfix
	 * @param context
	 * @param resizealertbodypostfix
	 */
	public final void setResizeAlertBodyPostfix(IContext context, String resizealertbodypostfix)
	{
		getMendixObject().setValue(context, MemberNames.ResizeAlertBodyPostfix.toString(), resizealertbodypostfix);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.AppleMessage that = (pushnotifications.proxies.AppleMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "PushNotifications.AppleMessage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
