// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

/**
 * Google implementation.
 */
public class GCMSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gCMSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.GCMSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Enabled("Enabled"),
		XMPPServer("XMPPServer"),
		XMPPPort("XMPPPort"),
		SenderId("SenderId"),
		APIKey("APIKey"),
		DTAPMode("DTAPMode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GCMSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.GCMSettings"));
	}

	protected GCMSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gCMSettingsMendixObject)
	{
		if (gCMSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.GCMSettings", gCMSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.GCMSettings");

		this.gCMSettingsMendixObject = gCMSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GCMSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pushnotifications.proxies.GCMSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.GCMSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.GCMSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.GCMSettings(context, mendixObject);
	}

	public static pushnotifications.proxies.GCMSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.GCMSettings.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.GCMSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pushnotifications.proxies.GCMSettings> result = new java.util.ArrayList<pushnotifications.proxies.GCMSettings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PushNotifications.GCMSettings" + xpathConstraint))
			result.add(pushnotifications.proxies.GCMSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Enabled
	 */
	public final Boolean getEnabled()
	{
		return getEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of Enabled
	 */
	public final Boolean getEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.Enabled.toString());
	}

	/**
	 * Set value of Enabled
	 * @param enabled
	 */
	public final void setEnabled(Boolean enabled)
	{
		setEnabled(getContext(), enabled);
	}

	/**
	 * Set value of Enabled
	 * @param context
	 * @param enabled
	 */
	public final void setEnabled(com.mendix.systemwideinterfaces.core.IContext context, Boolean enabled)
	{
		getMendixObject().setValue(context, MemberNames.Enabled.toString(), enabled);
	}

	/**
	 * @return value of XMPPServer
	 */
	public final String getXMPPServer()
	{
		return getXMPPServer(getContext());
	}

	/**
	 * @param context
	 * @return value of XMPPServer
	 */
	public final String getXMPPServer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.XMPPServer.toString());
	}

	/**
	 * Set value of XMPPServer
	 * @param xmppserver
	 */
	public final void setXMPPServer(String xmppserver)
	{
		setXMPPServer(getContext(), xmppserver);
	}

	/**
	 * Set value of XMPPServer
	 * @param context
	 * @param xmppserver
	 */
	public final void setXMPPServer(com.mendix.systemwideinterfaces.core.IContext context, String xmppserver)
	{
		getMendixObject().setValue(context, MemberNames.XMPPServer.toString(), xmppserver);
	}

	/**
	 * @return value of XMPPPort
	 */
	public final Integer getXMPPPort()
	{
		return getXMPPPort(getContext());
	}

	/**
	 * @param context
	 * @return value of XMPPPort
	 */
	public final Integer getXMPPPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.XMPPPort.toString());
	}

	/**
	 * Set value of XMPPPort
	 * @param xmppport
	 */
	public final void setXMPPPort(Integer xmppport)
	{
		setXMPPPort(getContext(), xmppport);
	}

	/**
	 * Set value of XMPPPort
	 * @param context
	 * @param xmppport
	 */
	public final void setXMPPPort(com.mendix.systemwideinterfaces.core.IContext context, Integer xmppport)
	{
		getMendixObject().setValue(context, MemberNames.XMPPPort.toString(), xmppport);
	}

	/**
	 * @return value of SenderId
	 */
	public final Long getSenderId()
	{
		return getSenderId(getContext());
	}

	/**
	 * @param context
	 * @return value of SenderId
	 */
	public final Long getSenderId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.SenderId.toString());
	}

	/**
	 * Set value of SenderId
	 * @param senderid
	 */
	public final void setSenderId(Long senderid)
	{
		setSenderId(getContext(), senderid);
	}

	/**
	 * Set value of SenderId
	 * @param context
	 * @param senderid
	 */
	public final void setSenderId(com.mendix.systemwideinterfaces.core.IContext context, Long senderid)
	{
		getMendixObject().setValue(context, MemberNames.SenderId.toString(), senderid);
	}

	/**
	 * @return value of APIKey
	 */
	public final String getAPIKey()
	{
		return getAPIKey(getContext());
	}

	/**
	 * @param context
	 * @return value of APIKey
	 */
	public final String getAPIKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.APIKey.toString());
	}

	/**
	 * Set value of APIKey
	 * @param apikey
	 */
	public final void setAPIKey(String apikey)
	{
		setAPIKey(getContext(), apikey);
	}

	/**
	 * Set value of APIKey
	 * @param context
	 * @param apikey
	 */
	public final void setAPIKey(com.mendix.systemwideinterfaces.core.IContext context, String apikey)
	{
		getMendixObject().setValue(context, MemberNames.APIKey.toString(), apikey);
	}

	/**
	 * Set value of DTAPMode
	 * @param dtapmode
	 */
	public final communitycommons.proxies.DTAPMode getDTAPMode()
	{
		return getDTAPMode(getContext());
	}

	/**
	 * @param context
	 * @return value of DTAPMode
	 */
	public final communitycommons.proxies.DTAPMode getDTAPMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DTAPMode.toString());
		if (obj == null)
			return null;

		return communitycommons.proxies.DTAPMode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DTAPMode
	 * @param dtapmode
	 */
	public final void setDTAPMode(communitycommons.proxies.DTAPMode dtapmode)
	{
		setDTAPMode(getContext(), dtapmode);
	}

	/**
	 * Set value of DTAPMode
	 * @param context
	 * @param dtapmode
	 */
	public final void setDTAPMode(com.mendix.systemwideinterfaces.core.IContext context, communitycommons.proxies.DTAPMode dtapmode)
	{
		if (dtapmode != null)
			getMendixObject().setValue(context, MemberNames.DTAPMode.toString(), dtapmode.toString());
		else
			getMendixObject().setValue(context, MemberNames.DTAPMode.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gCMSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.GCMSettings that = (pushnotifications.proxies.GCMSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.GCMSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
