// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class GoogleMessage extends pushnotifications.proxies.Message
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "PushNotifications.GoogleMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TimeToLive("TimeToLive"),
		Title("Title"),
		DeviceType("DeviceType"),
		To("To"),
		MessageId("MessageId"),
		Message("Message"),
		Failed("Failed"),
		FailedReason("FailedReason"),
		FailedCount("FailedCount"),
		NextTry("NextTry"),
		Queued("Queued");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public GoogleMessage(IContext context)
	{
		this(context, Core.instantiate(context, "PushNotifications.GoogleMessage"));
	}

	protected GoogleMessage(IContext context, IMendixObject googleMessageMendixObject)
	{
		super(context, googleMessageMendixObject);
		if (!Core.isSubClassOf("PushNotifications.GoogleMessage", googleMessageMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a PushNotifications.GoogleMessage");
	}

	/**
	 * @deprecated Use 'GoogleMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pushnotifications.proxies.GoogleMessage initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return pushnotifications.proxies.GoogleMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.GoogleMessage initialize(IContext context, IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.GoogleMessage(context, mendixObject);
	}

	public static pushnotifications.proxies.GoogleMessage load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.GoogleMessage.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.GoogleMessage> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<pushnotifications.proxies.GoogleMessage> result = new java.util.ArrayList<pushnotifications.proxies.GoogleMessage>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//PushNotifications.GoogleMessage" + xpathConstraint))
			result.add(pushnotifications.proxies.GoogleMessage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of TimeToLive
	 */
	public final Long getTimeToLive()
	{
		return getTimeToLive(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeToLive
	 */
	public final Long getTimeToLive(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.TimeToLive.toString());
	}

	/**
	 * Set value of TimeToLive
	 * @param timetolive
	 */
	public final void setTimeToLive(Long timetolive)
	{
		setTimeToLive(getContext(), timetolive);
	}

	/**
	 * Set value of TimeToLive
	 * @param context
	 * @param timetolive
	 */
	public final void setTimeToLive(IContext context, Long timetolive)
	{
		getMendixObject().setValue(context, MemberNames.TimeToLive.toString(), timetolive);
	}

	/**
	 * @return value of Title
	 */
	public final String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final String getTitle(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(IContext context, String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.GoogleMessage that = (pushnotifications.proxies.GoogleMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "PushNotifications.GoogleMessage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
