// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

public class SendResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sendResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.SendResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Message_id("Message_id"),
		Registration_id("Registration_id"),
		Error("Error"),
		SendResult_Root("PushNotifications.SendResult_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SendResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.SendResult"));
	}

	protected SendResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sendResultMendixObject)
	{
		if (sendResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.SendResult", sendResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.SendResult");

		this.sendResultMendixObject = sendResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SendResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pushnotifications.proxies.SendResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.SendResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.SendResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.SendResult(context, mendixObject);
	}

	public static pushnotifications.proxies.SendResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.SendResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Message_id
	 */
	public final String getMessage_id()
	{
		return getMessage_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_id
	 */
	public final String getMessage_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Message_id.toString());
	}

	/**
	 * Set value of Message_id
	 * @param message_id
	 */
	public final void setMessage_id(String message_id)
	{
		setMessage_id(getContext(), message_id);
	}

	/**
	 * Set value of Message_id
	 * @param context
	 * @param message_id
	 */
	public final void setMessage_id(com.mendix.systemwideinterfaces.core.IContext context, String message_id)
	{
		getMendixObject().setValue(context, MemberNames.Message_id.toString(), message_id);
	}

	/**
	 * @return value of Registration_id
	 */
	public final String getRegistration_id()
	{
		return getRegistration_id(getContext());
	}

	/**
	 * @param context
	 * @return value of Registration_id
	 */
	public final String getRegistration_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Registration_id.toString());
	}

	/**
	 * Set value of Registration_id
	 * @param registration_id
	 */
	public final void setRegistration_id(String registration_id)
	{
		setRegistration_id(getContext(), registration_id);
	}

	/**
	 * Set value of Registration_id
	 * @param context
	 * @param registration_id
	 */
	public final void setRegistration_id(com.mendix.systemwideinterfaces.core.IContext context, String registration_id)
	{
		getMendixObject().setValue(context, MemberNames.Registration_id.toString(), registration_id);
	}

	/**
	 * @return value of Error
	 */
	public final String getError()
	{
		return getError(getContext());
	}

	/**
	 * @param context
	 * @return value of Error
	 */
	public final String getError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Error.toString());
	}

	/**
	 * Set value of Error
	 * @param error
	 */
	public final void setError(String error)
	{
		setError(getContext(), error);
	}

	/**
	 * Set value of Error
	 * @param context
	 * @param error
	 */
	public final void setError(com.mendix.systemwideinterfaces.core.IContext context, String error)
	{
		getMendixObject().setValue(context, MemberNames.Error.toString(), error);
	}

	/**
	 * @return value of SendResult_Root
	 */
	public final pushnotifications.proxies.Root getSendResult_Root() throws com.mendix.core.CoreException
	{
		return getSendResult_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of SendResult_Root
	 */
	public final pushnotifications.proxies.Root getSendResult_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pushnotifications.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SendResult_Root.toString());
		if (identifier != null)
			result = pushnotifications.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SendResult_Root
	 * @param sendresult_root
	 */
	public final void setSendResult_Root(pushnotifications.proxies.Root sendresult_root)
	{
		setSendResult_Root(getContext(), sendresult_root);
	}

	/**
	 * Set value of SendResult_Root
	 * @param context
	 * @param sendresult_root
	 */
	public final void setSendResult_Root(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.Root sendresult_root)
	{
		if (sendresult_root == null)
			getMendixObject().setValue(context, MemberNames.SendResult_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SendResult_Root.toString(), sendresult_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sendResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.SendResult that = (pushnotifications.proxies.SendResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.SendResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
