// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

public class UpdateDeviceRegistration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject updateDeviceRegistrationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.UpdateDeviceRegistration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OldRegistrationId("OldRegistrationId"),
		NewRegistrationId("NewRegistrationId");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UpdateDeviceRegistration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.UpdateDeviceRegistration"));
	}

	protected UpdateDeviceRegistration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject updateDeviceRegistrationMendixObject)
	{
		if (updateDeviceRegistrationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.UpdateDeviceRegistration", updateDeviceRegistrationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.UpdateDeviceRegistration");

		this.updateDeviceRegistrationMendixObject = updateDeviceRegistrationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UpdateDeviceRegistration.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static pushnotifications.proxies.UpdateDeviceRegistration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.UpdateDeviceRegistration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.UpdateDeviceRegistration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.UpdateDeviceRegistration(context, mendixObject);
	}

	public static pushnotifications.proxies.UpdateDeviceRegistration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.UpdateDeviceRegistration.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OldRegistrationId
	 */
	public final String getOldRegistrationId()
	{
		return getOldRegistrationId(getContext());
	}

	/**
	 * @param context
	 * @return value of OldRegistrationId
	 */
	public final String getOldRegistrationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.OldRegistrationId.toString());
	}

	/**
	 * Set value of OldRegistrationId
	 * @param oldregistrationid
	 */
	public final void setOldRegistrationId(String oldregistrationid)
	{
		setOldRegistrationId(getContext(), oldregistrationid);
	}

	/**
	 * Set value of OldRegistrationId
	 * @param context
	 * @param oldregistrationid
	 */
	public final void setOldRegistrationId(com.mendix.systemwideinterfaces.core.IContext context, String oldregistrationid)
	{
		getMendixObject().setValue(context, MemberNames.OldRegistrationId.toString(), oldregistrationid);
	}

	/**
	 * @return value of NewRegistrationId
	 */
	public final String getNewRegistrationId()
	{
		return getNewRegistrationId(getContext());
	}

	/**
	 * @param context
	 * @return value of NewRegistrationId
	 */
	public final String getNewRegistrationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.NewRegistrationId.toString());
	}

	/**
	 * Set value of NewRegistrationId
	 * @param newregistrationid
	 */
	public final void setNewRegistrationId(String newregistrationid)
	{
		setNewRegistrationId(getContext(), newregistrationid);
	}

	/**
	 * Set value of NewRegistrationId
	 * @param context
	 * @param newregistrationid
	 */
	public final void setNewRegistrationId(com.mendix.systemwideinterfaces.core.IContext context, String newregistrationid)
	{
		getMendixObject().setValue(context, MemberNames.NewRegistrationId.toString(), newregistrationid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return updateDeviceRegistrationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.UpdateDeviceRegistration that = (pushnotifications.proxies.UpdateDeviceRegistration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.UpdateDeviceRegistration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
