// This file was generated by Mendix Modeler 6.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the PushNotifications module

	/**
	* In Milliseconds
	*/
	public static Long getDeliveyRetryBaseInterval()
	{
		return (Long)Core.getConfiguration().getConstantValue("PushNotifications.DeliveyRetryBaseInterval");
	}

	public static String getGCMSendUrl()
	{
		return (String)Core.getConfiguration().getConstantValue("PushNotifications.GCMSendUrl");
	}

	public static String getLogNode()
	{
		return (String)Core.getConfiguration().getConstantValue("PushNotifications.LogNode");
	}

	public static Long getMaxFailedCount()
	{
		return (Long)Core.getConfiguration().getConstantValue("PushNotifications.MaxFailedCount");
	}

	/**
	* Number of characters of the registration ids to write in log messages.
	*/
	public static Long getRegistrationIdCutoff()
	{
		return (Long)Core.getConfiguration().getConstantValue("PushNotifications.RegistrationIdCutoff");
	}
}