name: Export module package
on:
  push:
    paths:
      - "module/**"
  pull_request:
    paths:
      - "module/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #4.7.1
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 #4.3.1

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
        with:
          repository: 'mendixlabs/mendix-gradle-plugin'
          path: 'mendix-gradle-plugin'
          ref: '114bde309b52b037583d95a9beffee18eb71b65f'
          ssh-key: ${{ secrets.MENDIX_GRADLE_PLUGIN_SSH }}
      - name: Build mendix-gradle-plugin
        run: |
          cd mendix-gradle-plugin
          echo "kotlin.jvm.target.validation.mode = IGNORE" >> gradle.properties
          ./gradlew build publishToMavenLocal

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Define MODULE_VERSION
        run: |
          MODULE_VERSION=$(./gradlew -q printModuleVersion)
          echo "Detected module version: $MODULE_VERSION"
          echo "MODULE_VERSION=$MODULE_VERSION" >> $GITHUB_ENV
      - name: Create output directory
        run: mkdir $GITHUB_WORKSPACE/out
      - name: Build module
        run: ./gradlew exportModule
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Marketplace release v${{env.MODULE_VERSION}}
          tag_name: v${{env.MODULE_VERSION}}
          body: |
            (insert release notes)
          draft: true
          prerelease: false
          files: |
            module/dist/PushNotifications-${{env.MODULE_VERSION}}.mpk
      - name: Archive results
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Results
          path: ${{ github.workspace }}/out/*
