name: Export module package
on:
  push:
    paths:
      - "module/**"
  pull_request:
    paths:
      - "module/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'mendixlabs/mendix-gradle-plugin'
          path: 'mendix-gradle-plugin'
          ref: '114bde309b52b037583d95a9beffee18eb71b65f'
          ssh-key: ${{ secrets.MENDIX_GRADLE_PLUGIN_SSH }}
          ssh-strict: false

      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #4.7.1
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 #4.3.1

      - name: Build mendix-gradle-plugin
        working-directory: mendix-gradle-plugin
        run: |
          echo "kotlin.jvm.target.validation.mode = IGNORE" >> gradle.properties
          ./gradlew build publishToMavenLocal

      - name: Define MODULE_VERSION
        run: |
          $env:MODULE_VERSION=$(./gradlew -q printModuleVersion)
          echo ("MODULE_VERSION=" + $env:MODULE_VERSION) >> $env:GITHUB_ENV
      - name: "Detected module version"
        run: echo $env:MODULE_VERSION
      - name: Build module
        run: ./gradlew buildModule
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: PushNotifications-${{ env.MODULE_VERSION }}.mpk
          path: module/dist/PushNotifications-${{ env.MODULE_VERSION }}.mpk
          compression-level: 0