name: Publish Mendix Gradle plugin
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'mendixlabs/mendix-gradle-plugin'
          ref: '114bde309b52b037583d95a9beffee18eb71b65f'
          ssh-key: ${{ secrets.MENDIX_GRADLE_PLUGIN_SSH }}
          ssh-strict: false
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: repo
          sparse-checkout: .github/gradle
      - run: cp repo/.github/gradle/publish-mendix-gradle-plugin.gradle ./
      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #4.7.1
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 #4.3.1
      - name: Build mendix-gradle-plugin
        run: |
          echo "kotlin.jvm.target.validation.mode = IGNORE" >> gradle.properties
          ./gradlew -I publish-mendix-gradle-plugin.gradle build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
